
# This needs to point to the directory which levmar was installed.
# It should contain the .o object files generated by levmar as well as the .h
# header files.
LEVMAR_DIRECTORY = /home/michael/install/levmar

# Comment this out if levmar was not compiled with lapack
LEVMAR_FLAGS = -llapack -u MAIN__

# Directory for OpenCV include files.
# When using MacPorts, in my experience, the include files for OpenCV are
# located at "/opt/local/include/opencv".
OPENCV_INCLUDE_DIRECTORY=/usr/local/include/opencv
